SCR_MissionHeaderCampaign {
 World "{B85B3E6D9A135B2F}Worlds/MP/RedlineKolguyev.ent"
 SystemsConfig "{7C9E720397CC6ACD}Configs/Systems/ConflictSystems.conf"
 m_sName "Redline Reforged"
 m_sAuthor "RRG Team for SDG"
 m_sPath "{29D70E393B08E453}Missions/Redline_Reforged_SDG.conf"
 m_sDescription "ConflictReforged"
 m_sDetails "Original mod since 2013 on Arma 3"
 m_sIcon "{57EDB3DFE74302E4}UI/Textures/MissionThumbnails/logoredlinereforged.edds"
 m_sLoadingScreen "{A24DAAD52234F8FB}UI/Textures/MissionLoadingScreens/default.edds"
 m_sPreviewImage "{A24DAAD52234F8FB}UI/Textures/MissionLoadingScreens/default.edds"
 m_sGameMode "#AR-Campaign_GamemodeName"
 m_iPlayerCount 128
 m_eEditableGameFlags 6
 m_eDefaultGameFlags 6
 m_iControlPointsCap 6
 m_fVictoryTimeout 600
}