SCR_MissionHeaderCampaign {
 World "{63AB8A237B2D7A2C}Worlds/MP/Everon_Redline_SDG.ent"
 SystemsConfig "{7C9E720397CC6ACD}Configs/Systems/ConflictSystems.conf"
 m_sName "Redline Reforged"
 m_sAuthor "RRG Team for SDG and Everon mapping by Marius"
 m_sPath "{29D70E393B08E453}Missions/Redline_Reforged_SDG.conf"
 m_sDescription "ConflictReforged"
 m_sDetails "Original mod since 2013 on Arma 3"
 m_sIcon "{E996D87581BA7B30}UI/logoredlinereforged.edds"
 m_sLoadingScreen "{E996D87581BA7B30}UI/logoredlinereforged.edds"
 m_sPreviewImage "{0AC8F92569CA6E69}UI/red_roosters_variant_2.edds"
 m_sGameMode "#AR-Campaign_GamemodeName"
 m_iPlayerCount 128
 m_eEditableGameFlags 6
 m_eDefaultGameFlags 6
 m_iControlPointsCap 6
 m_fVictoryTimeout 600
}