SCR_MissionHeaderCampaign {
 World "{8CA3317D36A0A126}Worlds/MP/Everon_Redline_SDG_V2.ent"
 SystemsConfig "{7C9E720397CC6ACD}Configs/Systems/ConflictSystems.conf"
 m_sName "SDG - Redline Reforged"
 m_sAuthor "RRG Team for SDG and Everon mapping by Marius"
 m_sPath "{29D70E393B08E453}Missions/Redline_Reforged_SDG.conf"
 m_sDescription "Conflict Redline Reforged"
 m_sDetails "Original mod since 2013 on Arma 3"
 m_sIcon "{E996D87581BA7B30}UI/logoredlinereforged.edds"
 m_sLoadingScreen "{1DDC00349AC543F8}UI/logo.edds"
 m_sPreviewImage "{DE4BEB1292564F17}UI/11034.edds"
 m_sGameMode "#AR-Campaign_GamemodeName"
 m_iPlayerCount 128
 m_eEditableGameFlags 6
 m_eDefaultGameFlags 6
 m_iStartingHours 6
 m_fNightTimeAcceleration 12
 m_iControlPointsCap 11
 m_fVictoryTimeout 600
 m_eStartingRank CORPORAL
}